# -*- coding: utf-8 -*-
# Modernized for Pisi 3.12 Project by Ergün
# Focus: Java 21+ Automation, Pathlib Integration, x86_64 Optimization

from pathlib import Path
import pisi.context as ctx
import pisi.actionsapi
import pisi.actionsapi.get as get
from pisi.actionsapi.shelltools import system, export, makedirs, copy, copytree
from pisi.util import join_path

# PMP: Modern Java Executable Template
EXEC_TEMPLATE = """#!/bin/sh
# PMP Java Wrapper Generated by Ergün
cd {work_dir}
exec java {java_args} -jar {jar_file} {exe_args} "$@"
"""

class JavaError(pisi.actionsapi.Error):
    """PMP: Java işlemlerine özel modernize edilmiş hata sınıfı."""
    def __init__(self, msg=''):
        super().__init__(msg)
        ctx.ui.error(f"Java Hatası: {msg}")

class CompileError(JavaError): pass
class InstallError(JavaError): pass
class DoJavadocError(JavaError): pass

def _generate_classpath(classpath_list):
    """PMP: Java CLASSPATH bilgisini /etc/env.d altına mühürler."""
    env_dir = Path(get.installDIR()) / "etc/env.d"
    makedirs(env_dir)
    
    env_file = env_dir / get.srcNAME()
    prefix = "CLASSPATH=" if not env_file.exists() else ":"
    
    with env_file.open("a", encoding="utf-8") as f:
        f.write(f"{prefix}{':'.join(classpath_list)}")

def _generate_wrapper(dest_dir, jar_name, java_args, exe_args):
    """PMP: JAR dosyası için güvenli bir çalıştırılabilir wrapper üretir."""
    bin_dir = Path(get.installDIR()) / "usr/bin"
    makedirs(bin_dir)
    
    wrapper_path = bin_dir / get.srcNAME()
    content = EXEC_TEMPLATE.format(
        work_dir=f"/{dest_dir}",
        java_args=java_args,
        jar_file=jar_name,
        exe_args=exe_args
    )
    
    wrapper_path.write_text(content, encoding="utf-8")
    wrapper_path.chmod(0o755)

def compile(argument='build', parameters='', build_tool='ant'):
    """PMP: Ant, Maven veya Gradle ile Java projesini derler."""
    ctx.ui.info(f"[*] Java projesi derleniyor ({build_tool}): {get.srcNAME()}")
    run(argument, parameters, build_tool)

def installLib(src_pattern='*.jar', dest_path='/usr/share/java'):
    """JAR kütüphanelerini yerleştirir ve CLASSPATH'i günceller."""
    install_root = Path(get.installDIR())
    dest_dir = install_root / dest_path.lstrip("/")
    makedirs(dest_dir)
    
    classpath = []
    sources = list(Path(".").glob(src_pattern))
    
    if not sources:
        raise InstallError(f"Eşleşen JAR dosyası bulunamadı: {src_pattern}")

    for src in sources:
        target = dest_dir / src.name
        ctx.ui.info(f"[*] JAR kuruluyor: {src.name}")
        
        if src.is_file():
            copy(str(src), str(target))
            if src.suffix == '.jar':
                classpath.append(f"/{dest_path.strip('/')}/{src.name}")
        elif src.is_dir():
            copytree(str(src), str(target))
            # PMP: Alt dizinlerdeki JAR'ları rglob ile bul
            for jar in target.rglob("*.jar"):
                rel_path = f"/{Path(dest_path).strip('/')}/{jar.relative_to(dest_dir)}"
                classpath.append(rel_path)

    if classpath:
        _generate_classpath(classpath)

def installExe(jar_path, java_args='', exe_args='', dest_dir=None):
    """Çalıştırılabilir JAR dosyasını kurar ve wrapper oluşturur."""
    if not dest_dir:
        dest_dir = f"usr/share/java/{get.srcNAME()}"
        
    install_root = Path(get.installDIR())
    target_dir = install_root / dest_dir
    makedirs(target_dir)
    
    src_jar = Path(jar_path)
    copy(str(src_jar), str(target_dir / src_jar.name))
    
    _generate_wrapper(dest_dir, src_jar.name, java_args, exe_args)

def run(argument='', parameters='', build_tool='ant'):
    """PMP: Java build aracını PiSi bağlamında çalıştırır."""
    # Modern JDK yolları (x86_64)
    export('JAVA_HOME', '/usr/lib/jvm/default-java')
    export('LC_ALL', 'en_US.UTF-8')
    
    cmd = f"{build_tool} {parameters} {argument}".strip()
    if system(cmd):
        raise JavaError(f"Java komutu başarısız oldu: {cmd}")
